### ISSUE TITLE
Implement match statement for Bend Types in Python

### ISSUE THREAD

**Issue by vkobinski** [fglab-tech/benda#12]
This is a complex feature we need to implement, and due to PyO3 limitations and the crude Python API, it's hard.

PyO3 can generate the code necessary to implement pattern matching in Python, but only at compile time. Therefore, we need a way to figure out how PyO3 can generate this code and do it ourselves during runtime.

**Comment by steinerkelvin** [comment]
Can you link to docs and give some examples?

Can we fallback to something like if-else chains in the meantime?
